// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvegqdvpogmntygdjjvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2ZWdxZHZwb2dtbnR5Z2RqanZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwMjQ0MzcsImV4cCI6MjA4ODYwMDQzN30.SiyH5cuKWild1qxTcbr4h34M_Z-JiaS_iceeaA9HgQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});